PREFIX m2: <https://raw.githubusercontent.com/Echopraxium/tscg/main/ontology/M2_MetaConcepts.jsonld#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?category (COUNT(?ontology) AS ?count)
WHERE {
  ?ontology a owl:Ontology ;
            m2:ontologyCategory ?category .
}
GROUP BY ?category
ORDER BY ?category