PREFIX m2: <https://raw.githubusercontent.com/Echopraxium/tscg/main/ontology/M2_MetaConcepts.jsonld#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?ontology ?title ?created
WHERE {
  ?ontology a owl:Ontology ;
            m2:ontologyCategory "DomainExtension" ;
            dcterms:title ?title ;
            dcterms:created ?created .
}
ORDER BY ?created