// tsk-cc/src/parser.rs
// Author: Echopraxium with the collaboration of Claude AI
// Version: 0.3.0
//
// LLVM IR textual format parser.
// Handles the subset generated by: clang -O1 -emit-llvm -S wolf3d.c
//
// Strategy: line-by-line tokenizer, recursive descent per construct.
// No regex — manual scanning for speed and error clarity.

use anyhow::{anyhow, bail, Result};
use crate::ir::{IrType, Value, Instr, BinOpKind, IcmpPred, BasicBlock,
                Function, Global, GlobalInit, Module};

// ─────────────────────────────────────────────────────────────────────────────
// Token
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
enum Tok {
    Ident(String),      // bare word: define, ret, add, ...
    LocalReg(String),   // %name or %0 %1 ...
    GlobalRef(String),  // @name
    Integer(i64),
    LBrace, RBrace,
    LParen, RParen,
    LBracket, RBracket,
    Comma, Equals, Star, Colon,
    Eof,
}

struct Lexer<'a> {
    src: &'a str,
    pos: usize,
    line: usize,
}

impl<'a> Lexer<'a> {
    fn new(src: &'a str) -> Self { Self { src, pos: 0, line: 1 } }

    fn peek_ch(&self) -> Option<char> { self.src[self.pos..].chars().next() }

    fn advance_ch(&mut self) -> Option<char> {
        let ch = self.src[self.pos..].chars().next()?;
        self.pos += ch.len_utf8();
        if ch == '\n' { self.line += 1; }
        Some(ch)
    }

    fn skip_spaces(&mut self) {
        while let Some(c) = self.peek_ch() {
            if c == ' ' || c == '\t' || c == '\r' { self.advance_ch(); }
            else { break; }
        }
    }

    fn skip_line(&mut self) {
        while let Some(c) = self.advance_ch() {
            if c == '\n' { break; }
        }
    }

    fn read_word(&mut self) -> String {
        let mut s = String::new();
        while let Some(c) = self.peek_ch() {
            if c.is_alphanumeric() || c == '_' || c == '.' || c == '-' {
                s.push(c);
                self.advance_ch();
            } else { break; }
        }
        s
    }

    fn read_quoted(&mut self) -> String {
        // consume opening "
        self.advance_ch();
        let mut s = String::new();
        loop {
            match self.advance_ch() {
                Some('"') => break,
                Some('\\') => {
                    // LLVM IR / clang string escape handling:
                    //   \XX  (backslash + 2 hex digits) → byte 0xXX (LLVM hex escape)
                    //   \\  (two backslashes)           → one backslash 0x5C
                    //         (clang Linux encodes C-level \\ as \\\\ in IR)
                    //   otherwise                         → literal backslash
                    let h1 = self.peek_ch().unwrap_or('\0');
                    if h1 == '\\' {
                        // Two backslashes → one literal backslash
                        self.advance_ch(); // consume second backslash
                        s.push('\\');
                    } else {
                        // Try \XX hex escape
                        let h2 = {
                            let saved = self.pos;
                            self.advance_ch();
                            let c = self.peek_ch().unwrap_or('\0');
                            self.pos = saved;
                            c
                        };
                        let hex = format!("{}{}", h1, h2);
                        if let Ok(b) = u8::from_str_radix(&hex, 16) {
                            self.advance_ch(); // consume h1
                            self.advance_ch(); // consume h2
                            s.push(b as char);
                        } else {
                            // Not valid hex: treat as literal backslash
                            s.push('\\');
                        }
                    }
                }
                Some(c) => s.push(c),
                None => break,
            }
        }
        s
    }

    fn next_token(&mut self) -> Tok {
        loop {
            self.skip_spaces();
            match self.peek_ch() {
                None => return Tok::Eof,
                Some('\n') => { self.advance_ch(); continue; }
                Some(';') => { self.skip_line(); continue; }
                Some('{') => { self.advance_ch(); return Tok::LBrace; }
                Some('}') => { self.advance_ch(); return Tok::RBrace; }
                Some('(') => { self.advance_ch(); return Tok::LParen; }
                Some(')') => { self.advance_ch(); return Tok::RParen; }
                Some('[') => { self.advance_ch(); return Tok::LBracket; }
                Some(']') => { self.advance_ch(); return Tok::RBracket; }
                Some(',') => { self.advance_ch(); return Tok::Comma; }
                Some('=') => { self.advance_ch(); return Tok::Equals; }
                Some('*') => { self.advance_ch(); return Tok::Star; }
                Some(':') => { self.advance_ch(); return Tok::Colon; }
                Some('"') => {
                    let s = self.read_quoted();
                    return Tok::Ident(s);
                }
                Some('%') => {
                    self.advance_ch();
                    let name = self.read_word();
                    return Tok::LocalReg(name);
                }
                Some('@') => {
                    self.advance_ch();
                    let name = if self.peek_ch() == Some('"') {
                        self.read_quoted()
                    } else {
                        self.read_word()
                    };
                    return Tok::GlobalRef(name);
                }
                Some('-') => {
                    self.advance_ch();
                    let w = self.read_word();
                    if let Ok(n) = w.parse::<i64>() {
                        return Tok::Integer(-n);
                    }
                    return Tok::Ident(format!("-{}", w));
                }
                Some(c) if c.is_ascii_digit() => {
                    let w = self.read_word();
                    if let Ok(n) = w.parse::<i64>() {
                        return Tok::Integer(n);
                    }
                    return Tok::Ident(w);
                }
                Some(c) if c.is_alphabetic() || c == '!' => {
                    if c == '!' {
                        // metadata reference — skip to end of line
                        self.skip_line();
                        continue;
                    }
                    let w = self.read_word();
                    return Tok::Ident(w);
                }
                Some(c) => {
                    self.advance_ch();
                    // skip unknown chars (e.g. #, !, etc.)
                    let _ = c;
                    continue;
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Parser
// ─────────────────────────────────────────────────────────────────────────────

pub struct Parser {
    tokens:    Vec<Tok>,
    pos:       usize,
    /// Named struct type definitions: "struct.actor_t" → IrType::Struct([...])
    type_defs: std::collections::HashMap<String, IrType>,
}

impl Parser {
    pub fn new(src: &str) -> Self {
        let mut lex = Lexer::new(src);
        let mut tokens = Vec::new();
        loop {
            let t = lex.next_token();
            if t == Tok::Eof { tokens.push(Tok::Eof); break; }
            tokens.push(t);
        }
        Self { tokens, pos: 0, type_defs: std::collections::HashMap::new() }
    }

    fn peek(&self) -> &Tok {
        self.tokens.get(self.pos).unwrap_or(&Tok::Eof)
    }

    fn advance(&mut self) -> &Tok {
        let t = self.tokens.get(self.pos).unwrap_or(&Tok::Eof);
        if self.pos < self.tokens.len() - 1 { self.pos += 1; }
        t
    }

    fn expect_ident(&mut self) -> Result<String> {
        match self.advance().clone() {
            Tok::Ident(s) => Ok(s),
            t => bail!("expected ident, got {:?}", t),
        }
    }

    #[allow(dead_code)]
    fn expect_local(&mut self) -> Result<String> {
        match self.advance().clone() {
            Tok::LocalReg(s) => Ok(s),
            t => bail!("expected %reg, got {:?}", t),
        }
    }

    fn expect_integer(&mut self) -> Result<i64> {
        match self.advance().clone() {
            Tok::Integer(n) => Ok(n),
            Tok::Ident(s) => s.parse::<i64>().map_err(|_| anyhow!("expected integer, got '{}'", s)),
            t => bail!("expected integer, got {:?}", t),
        }
    }

    fn eat_ident(&mut self, expected: &str) -> bool {
        if matches!(self.peek(), Tok::Ident(s) if s == expected) {
            self.advance();
            true
        } else { false }
    }

    fn eat(&mut self, tok: &Tok) -> bool {
        if self.peek() == tok {
            self.advance();
            true
        } else { false }
    }

    // Skip tokens until we hit a known keyword or EOF (error recovery)
    fn skip_to_keyword(&mut self, keywords: &[&str]) {
        loop {
            match self.peek() {
                Tok::Eof => break,
                Tok::Ident(s) if keywords.contains(&s.as_str()) => break,
                Tok::RBrace => break,
                // Stop on global refs so @tilemap is not skipped
                Tok::GlobalRef(_) => break,
                _ => { self.advance(); }
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Type parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_type(&mut self) -> Result<IrType> {
        match self.peek().clone() {
            Tok::Ident(s) => {
                self.advance();
                match s.as_str() {
                    "void" => Ok(IrType::Void),
                    "i1"   => Ok(IrType::I1),
                    "i8"   => Ok(IrType::I8),
                    "i16"  => Ok(IrType::I16),
                    "i32"  => Ok(IrType::I32),
                    "i64"  => Ok(IrType::I64),
                    "ptr"  => {
                        // opaque pointer — skip optional addrspace
                        Ok(IrType::Ptr)
                    }
                    other => {
                        // Unknown type — treat as i64 (conservative)
                        log::warn!("unknown type '{}', treating as i64", other);
                        Ok(IrType::I64)
                    }
                }
            }
            Tok::LBracket => {
                // [N x T]
                self.advance();
                let n = self.expect_integer()? as usize;
                self.eat_ident("x");
                let t = self.parse_type()?;
                self.eat(&Tok::RBracket);
                Ok(IrType::Array(n, Box::new(t)))
            }
            Tok::LBrace => {
                // { T1, T2, ... }
                self.advance();
                let mut fields = Vec::new();
                loop {
                    if self.eat(&Tok::RBrace) { break; }
                    fields.push(self.parse_type()?);
                    if !self.eat(&Tok::Comma) {
                        self.eat(&Tok::RBrace);
                        break;
                    }
                }
                Ok(IrType::Struct(fields))
            }
            Tok::LocalReg(name) => {
                // %struct.foo — look up in type_defs; if not yet defined, emit Named for
                // later resolution by FuncGen::resolve_type (handles forward references).
                let name = name.clone();
                self.advance();
                if let Some(ty) = self.type_defs.get(&name).cloned() {
                    log::debug!("named struct type %{} → {:?}", name, ty);
                    Ok(ty)
                } else {
                    log::debug!("named struct type %{} → Named (forward ref)", name);
                    Ok(IrType::Named(name))
                }
            }
            _ => Ok(IrType::I64), // fallback
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Value parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_value(&mut self) -> Result<Value> {
        match self.peek().clone() {
            Tok::LocalReg(s)  => { self.advance(); Ok(Value::Reg(s)) }
            Tok::GlobalRef(s) => { self.advance(); Ok(Value::Global(s)) }
            Tok::Integer(n)   => { self.advance(); Ok(Value::Const(n)) }
            Tok::Ident(s) => {
                self.advance();
                match s.as_str() {
                    "null" | "zeroinitializer" => Ok(Value::Null),
                    "true"  => Ok(Value::Bool(true)),
                    "false" => Ok(Value::Bool(false)),
                    "undef" => Ok(Value::Undef),
                    // Inline GEP constant: getelementptr(type, ptr @global, i64 0, i64 N)
                    // Resolve to Value::Global(name) — codegen adds the const offset
                    "getelementptr" => {
                        self.skip_flags(); // inbounds
                        self.eat(&Tok::LParen);
                        // Skip element type
                        let _ = self.parse_type();
                        self.eat(&Tok::Comma);
                        // Base pointer: ptr @global
                        let _ = self.parse_type(); // ptr
                        let base = self.parse_value()?;
                        // Consume indices, compute constant offset
                        let mut const_offset: i64 = 0;
                        while self.eat(&Tok::Comma) {
                            let _ = self.parse_type();
                            match self.parse_value()? {
                                Value::Const(n) => { const_offset += n; }
                                _ => {}
                            }
                        }
                        self.eat(&Tok::RParen);
                        // Return as a GepConst variant encoded in Global name with offset
                        match base {
                            Value::Global(name) => {
                                if const_offset == 0 {
                                    Ok(Value::Global(name))
                                } else {
                                    // Encode as "name+offset" — codegen will split it
                                    Ok(Value::Global(format!("{}+{}", name, const_offset)))
                                }
                            }
                            other => Ok(other),
                        }
                    }
                    // Constant expression: inttoptr (i64 N to ptr) → Value::Const(N)
                    // Example: store ptr inttoptr (i64 1 to ptr), ptr %6
                    "inttoptr" => {
                        self.eat(&Tok::LParen);
                        let _ = self.parse_type();   // i64
                        let val = self.parse_value()?; // N
                        while !matches!(self.peek(), Tok::RParen | Tok::Eof) {
                            self.advance();
                        }
                        self.eat(&Tok::RParen);
                        Ok(val)  // treat inttoptr(i64 N) as Value::Const(N)
                    }
                    // Constant expression: ptrtoint (ptr @x to i64) → Value::Global(x)
                    "ptrtoint" => {
                        self.eat(&Tok::LParen);
                        let _ = self.parse_type();   // ptr
                        let val = self.parse_value()?; // @global or %reg
                        while !matches!(self.peek(), Tok::RParen | Tok::Eof) {
                            self.advance();
                        }
                        self.eat(&Tok::RParen);
                        Ok(val)
                    }
                    other => Ok(Value::Reg(other.to_string())),
                }
            }
            _ => Ok(Value::Undef),
        }
    }

    // Parse "type value" pair
    fn parse_typed_value(&mut self) -> Result<(IrType, Value)> {
        let ty  = self.parse_type()?;
        let val = self.parse_value()?;
        Ok((ty, val))
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Skip flag keywords (nsw, nuw, exact, inbounds, etc.)
    // ─────────────────────────────────────────────────────────────────────────

    fn skip_flags(&mut self) {
        loop {
            match self.peek() {
                Tok::Ident(s) if matches!(s.as_str(),
                    "nsw"|"nuw"|"exact"|"inbounds"|"volatile"|
                    "noundef"|"nocapture"|"noalias"|"readonly"|"writeonly"|
                    "nneg"|"local_unnamed_addr"|"dso_local"|"align" ) => {
                    let s = s.clone();
                    self.advance();
                    // align N — consume the number too
                    if s == "align" { let _ = self.expect_integer(); }
                }
                _ => break,
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Instruction parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_instr(&mut self, dst: Option<String>) -> Result<Instr> {
        let op = self.expect_ident()?;

        match op.as_str() {

            // ── Binary operations ─────────────────────────────────────────
            op_str if BinOpKind::from_str(op_str).is_some() => {
                let op = BinOpKind::from_str(op_str).unwrap();
                self.skip_flags();
                let ty  = self.parse_type()?;
                let lhs = self.parse_value()?;
                self.eat(&Tok::Comma);
                // rhs has no type prefix
                let rhs = self.parse_value()?;
                Ok(Instr::BinOp {
                    dst: dst.unwrap_or_default(), op, ty, lhs, rhs
                })
            }

            // ── ICmp ─────────────────────────────────────────────────────
            "icmp" => {
                let pred_str = self.expect_ident()?;
                let pred = IcmpPred::from_str(&pred_str)
                    .ok_or_else(|| anyhow!("unknown icmp predicate '{}'", pred_str))?;
                let ty  = self.parse_type()?;
                let lhs = self.parse_value()?;
                self.eat(&Tok::Comma);
                let rhs = self.parse_value()?;
                Ok(Instr::ICmp { dst: dst.unwrap_or_default(), pred, ty, lhs, rhs })
            }

            // ── Branch ───────────────────────────────────────────────────
            "br" => {
                match self.peek().clone() {
                    Tok::Ident(s) if s == "label" => {
                        self.advance();
                        let target = match self.advance().clone() {
                            Tok::LocalReg(s) => s,
                            t => bail!("expected label name, got {:?}", t),
                        };
                        Ok(Instr::BrUncond { target })
                    }
                    Tok::Ident(s) if s == "i1" => {
                        self.advance(); // consume i1
                        let cond = self.parse_value()?;
                        self.eat(&Tok::Comma);
                        self.eat_ident("label");
                        let then_bb = match self.advance().clone() {
                            Tok::LocalReg(s) => s,
                            t => bail!("expected then label, got {:?}", t),
                        };
                        self.eat(&Tok::Comma);
                        self.eat_ident("label");
                        let else_bb = match self.advance().clone() {
                            Tok::LocalReg(s) => s,
                            t => bail!("expected else label, got {:?}", t),
                        };
                        Ok(Instr::BrCond { cond, then_bb, else_bb })
                    }
                    _ => bail!("malformed br"),
                }
            }


            // ── Switch ───────────────────────────────────────────────────
            "switch" => {
                let _ty = self.parse_type()?;
                let cond = self.parse_value()?;
                self.eat(&Tok::Comma);
                self.eat_ident("label");
                let default_bb = match self.advance().clone() {
                    Tok::LocalReg(s) => s,
                    t => bail!("switch: expected default label, got {:?}", t),
                };
                let mut cases = Vec::new();
                if self.eat(&Tok::LBracket) {
                    loop {
                        if self.eat(&Tok::RBracket) { break; }
                        let _case_ty = self.parse_type()?;
                        let val = match self.advance().clone() {
                            Tok::Integer(n) => n,
                            t => bail!("switch: expected case value, got {:?}", t),
                        };
                        self.eat(&Tok::Comma);
                        self.eat_ident("label");
                        let bb = match self.advance().clone() {
                            Tok::LocalReg(s) => s,
                            t => bail!("switch: expected case label, got {:?}", t),
                        };
                        cases.push((val, bb));
                        self.eat(&Tok::Comma);
                    }
                }
                Ok(Instr::Switch { cond, default_bb, cases })
            }

            // ── PHI ──────────────────────────────────────────────────────
            "phi" => {
                let ty = self.parse_type()?;
                let mut incoming = Vec::new();
                loop {
                    if !self.eat(&Tok::LBracket) { break; }
                    let val   = self.parse_value()?;
                    self.eat(&Tok::Comma);
                    let label = match self.advance().clone() {
                        Tok::LocalReg(s) => s,
                        t => bail!("phi: expected label, got {:?}", t),
                    };
                    self.eat(&Tok::RBracket);
                    incoming.push((val, label));
                    if !self.eat(&Tok::Comma) { break; }
                    // peek — if next is not '[' we're done
                    if !matches!(self.peek(), Tok::LBracket) { break; }
                }
                Ok(Instr::Phi { dst: dst.unwrap_or_default(), ty, incoming })
            }

            // ── Alloca ───────────────────────────────────────────────────
            "alloca" => {
                let ty = self.parse_type()?;
                let mut align = ty.byte_size().max(1);
                // optional , align N
                if self.eat(&Tok::Comma) {
                    if self.eat_ident("align") {
                        align = self.expect_integer()? as usize;
                    } else {
                        // could be count: alloca i32, i32 4
                        let _ = self.parse_type();
                        let _ = self.parse_value();
                    }
                }
                Ok(Instr::Alloca { dst: dst.unwrap_or_default(), ty, align })
            }

            // ── Load ─────────────────────────────────────────────────────
            "load" => {
                self.skip_flags();
                let ty  = self.parse_type()?;
                self.eat(&Tok::Comma);
                let (_ptr_ty, ptr) = self.parse_typed_value()?;
                let mut align = ty.byte_size().max(1);
                if self.eat(&Tok::Comma) && self.eat_ident("align") {
                    align = self.expect_integer()? as usize;
                }
                // skip !tbaa metadata
                Ok(Instr::Load { dst: dst.unwrap_or_default(), ty, ptr, align })
            }

            // ── Store ────────────────────────────────────────────────────
            "store" => {
                self.skip_flags();
                let (ty, val) = self.parse_typed_value()?;
                self.eat(&Tok::Comma);
                let (_ptr_ty, ptr) = self.parse_typed_value()?;
                let mut align = ty.byte_size().max(1);
                if self.eat(&Tok::Comma) && self.eat_ident("align") {
                    align = self.expect_integer()? as usize;
                }
                Ok(Instr::Store { ty, val, ptr, align })
            }

            // ── GEP ──────────────────────────────────────────────────────
            "getelementptr" => {
                self.skip_flags(); // inbounds
                let elem_ty = self.parse_type()?;
                self.eat(&Tok::Comma);
                let (_base_ty, ptr) = self.parse_typed_value()?;
                let mut indices = Vec::new();
                while self.eat(&Tok::Comma) {
                    let (_idx_ty, idx) = self.parse_typed_value()?;
                    indices.push(idx);
                }
                Ok(Instr::Gep { dst: dst.unwrap_or_default(), elem_ty, ptr, indices })
            }

            // ── Casts ────────────────────────────────────────────────────
            "zext" => {
                self.skip_flags();
                let from_ty = self.parse_type()?;
                let val     = self.parse_value()?;
                self.eat_ident("to");
                let to_ty = self.parse_type()?;
                Ok(Instr::Zext { dst: dst.unwrap_or_default(), from_ty, val, to_ty })
            }
            "sext" => {
                self.skip_flags();
                let from_ty = self.parse_type()?;
                let val     = self.parse_value()?;
                self.eat_ident("to");
                let to_ty = self.parse_type()?;
                Ok(Instr::Sext { dst: dst.unwrap_or_default(), from_ty, val, to_ty })
            }
            "trunc" => {
                self.skip_flags();
                let from_ty = self.parse_type()?;
                let val     = self.parse_value()?;
                self.eat_ident("to");
                let to_ty = self.parse_type()?;
                Ok(Instr::Trunc { dst: dst.unwrap_or_default(), from_ty, val, to_ty })
            }
            "bitcast" | "ptrtoint" | "inttoptr" => {
                let from_ty = self.parse_type()?;
                let val     = self.parse_value()?;
                self.eat_ident("to");
                let to_ty = self.parse_type()?;
                match op.as_str() {
                    "bitcast"  => Ok(Instr::Bitcast  { dst: dst.unwrap_or_default(), from_ty, val, to_ty }),
                    "ptrtoint" => Ok(Instr::PtrToInt { dst: dst.unwrap_or_default(), val, to_ty }),
                    _          => Ok(Instr::IntToPtr { dst: dst.unwrap_or_default(), val, to_ty }),
                }
            }

            // ── Call ─────────────────────────────────────────────────────
            // ── Select (C ternary) ────────────────────────────────────────
            // %r = select i1 %cond, ty %true_val, ty %false_val
            "select" => {
                self.skip_flags();
                let _cond_ty = self.parse_type()?;  // always i1
                let cond = self.parse_value()?;
                self.eat(&Tok::Comma);
                let ty = self.parse_type()?;
                let true_val = self.parse_value()?;
                self.eat(&Tok::Comma);
                let _false_ty = self.parse_type()?;
                let false_val = self.parse_value()?;
                Ok(Instr::Select {
                    dst: dst.unwrap_or_default(),
                    cond, ty, true_val, false_val,
                })
            }

            // ── Call ─────────────────────────────────────────────────────
            "call" | "tail" | "musttail" => {
                if op != "call" { self.eat_ident("call"); }
                self.skip_flags();
                let ret_ty = self.parse_type()?;
                // Handle LLVM variadic call syntax: call i32 (ptr, ...) @func(args)
                // After the return type, if we see '(' it's a function type signature
                // (not a value). Skip it entirely and then parse the actual function value.
                // Example: call i32 (ptr, ...) @printf(...)
                //                   ^^^^^^^^^^  ← skip this
                if matches!(self.peek(), Tok::LParen) {
                    let mut depth = 0i32;
                    loop {
                        match self.peek() {
                            Tok::LParen => { depth += 1; self.advance(); }
                            Tok::RParen => {
                                self.advance();
                                depth -= 1;
                                if depth <= 0 { break; }
                            }
                            Tok::Eof => break,
                            _ => { self.advance(); }
                        }
                    }
                }
                let func = self.parse_value()?;
                // argument list
                self.eat(&Tok::LParen);
                let mut args = Vec::new();
                loop {
                    if self.eat(&Tok::RParen) { break; }
                    self.skip_flags();
                    let ty  = self.parse_type()?;
                    self.skip_flags();
                    let val = self.parse_value()?;
                    args.push((ty, val));
                    if !self.eat(&Tok::Comma) {
                        self.eat(&Tok::RParen);
                        break;
                    }
                }
                // Intercept LLVM intrinsics before emitting a Call node
                if let Value::Global(ref fname) = func {
                    // llvm.memset.p0.i64 / llvm.memset.p0i8.i64 etc.
                    if fname.starts_with("llvm.memset") && args.len() >= 3 {
                        let dst_ptr  = args[0].1.clone();
                        let byte_val = args[1].1.clone();
                        let len      = args[2].1.clone();
                        return Ok(Instr::MemSet { dst_ptr, byte_val, len });
                    }
                    // llvm.memcpy.p0.p0.i64 etc.
                    if fname.starts_with("llvm.memcpy") && args.len() >= 3 {
                        let dst_ptr = args[0].1.clone();
                        let src_ptr = args[1].1.clone();
                        let len     = args[2].1.clone();
                        return Ok(Instr::MemCpy { dst_ptr, src_ptr, len });
                    }
                    // llvm.va_start.p0(ptr %slot) — capture vararg area pointer
                    if fname.starts_with("llvm.va_start") && args.len() >= 1 {
                        let slot = args[0].1.clone();
                        return Ok(Instr::VaStart { slot });
                    }
                    // llvm.va_end.p0(ptr %slot) — no-op on TriskeleVM
                    if fname.starts_with("llvm.va_end") {
                        return Ok(Instr::Unreachable);
                    }
                    // llvm.abs.i32 / llvm.abs.i64 — abs(val)
                    // Signature: i32 @llvm.abs.i32(i32 %val, i1 immarg %is_poison)
                    // We ignore the is_poison flag (always false in clang -O0).
                    if fname.starts_with("llvm.abs") && args.len() >= 1 {
                        let val = args[0].1.clone();
                        let ty  = args[0].0.clone();
                        let d   = dst.unwrap_or_else(|| "__abs_unused".to_string());
                        return Ok(Instr::Abs { dst: d, ty, val });
                    }
                    // Windows CRT: __acrt_iob_func(n) — returns FILE* (stderr=2, stdout=1)
                    // We return a sentinel value; tsk-libc fprintf ignores the FILE* arg.
                    if fname == "__acrt_iob_func" {
                        // dst = sentinel constant 0xE0 (libc area — not dereferenced)
                        if let Some(ref d) = dst {
                            return Ok(Instr::BinOp {
                                dst: d.clone(),
                                op: crate::ir::BinOpKind::Or,
                                ty: IrType::Ptr,
                                lhs: Value::Const(0xE000_0000),
                                rhs: Value::Const(0),
                            });
                        }
                        return Ok(Instr::Unreachable);
                    }
                    // Windows CRT vprintf family — redirect to tsk-libc syscalls.
                    // _vfprintf_l(file, fmt, locale, va_ptr) → fprintf(file, fmt, va_ptr_args...)
                    // _vsprintf_l(buf, fmt, locale, va_ptr)  → sprintf(buf, fmt, va_ptr_args...)
                    // _vsnprintf_l(buf,n,fmt,locale,va_ptr)  → sprintf(buf, fmt, va_ptr_args...)
                    // __stdio_common_vfprintf(opts,file,fmt,locale,va_ptr) → fprintf
                    // __stdio_common_vsprintf(opts,buf,n,fmt,locale,va_ptr) → sprintf
                    // Strategy: rewrite as Call to our tsk-libc symbol with remapped args.
                    if fname == "_vfprintf_l" || fname == "__stdio_common_vfprintf" {
                        // Map to @fprintf(file, fmt, va_ptr) — tsk-libc 0x41 handles it
                        let (file_arg, fmt_arg, va_arg) = if fname == "_vfprintf_l" {
                            // _vfprintf_l(file, fmt, locale, va_ptr)
                            (args.get(0).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(1).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(3).map(|a| a.1.clone()).unwrap_or(Value::Const(0)))
                        } else {
                            // __stdio_common_vfprintf(opts, file, fmt, locale, va_ptr)
                            (args.get(1).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(2).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(4).map(|a| a.1.clone()).unwrap_or(Value::Const(0)))
                        };
                        return Ok(Instr::Call {
                            dst,
                            ret_ty: IrType::I32,
                            func: Value::Global("vfprintf".to_string()),
                            args: vec![
                                (IrType::Ptr, file_arg),
                                (IrType::Ptr, fmt_arg),
                                (IrType::Ptr, va_arg),
                            ],
                        });
                    }
                    if fname == "_vsprintf_l" || fname == "_vsnprintf_l"
                        || fname == "__stdio_common_vsprintf"
                    {
                        // Map to @sprintf(buf, fmt, va_ptr)
                        let (buf_arg, fmt_arg, va_arg) = if fname == "_vsprintf_l" {
                            // _vsprintf_l(buf, fmt, locale, va_ptr)
                            (args.get(0).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(1).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(3).map(|a| a.1.clone()).unwrap_or(Value::Const(0)))
                        } else if fname == "_vsnprintf_l" {
                            // _vsnprintf_l(buf, n, fmt, locale, va_ptr)
                            (args.get(0).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(2).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(4).map(|a| a.1.clone()).unwrap_or(Value::Const(0)))
                        } else {
                            // __stdio_common_vsprintf(opts, buf, n, fmt, locale, va_ptr)
                            (args.get(1).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(3).map(|a| a.1.clone()).unwrap_or(Value::Const(0)),
                             args.get(5).map(|a| a.1.clone()).unwrap_or(Value::Const(0)))
                        };
                        return Ok(Instr::Call {
                            dst,
                            ret_ty: IrType::I32,
                            func: Value::Global("vsprintf".to_string()),
                            args: vec![
                                (IrType::Ptr, buf_arg),
                                (IrType::Ptr, fmt_arg),
                                (IrType::Ptr, va_arg),
                            ],
                        });
                    }
                    // llvm.lifetime.start/end, llvm.dbg.* — silently drop
                    if fname.starts_with("llvm.lifetime")
                        || fname.starts_with("llvm.dbg")
                        || fname.starts_with("llvm.assume")
                    {
                        return Ok(Instr::Unreachable);
                    }
                }
                Ok(Instr::Call { dst, ret_ty, func, args })
            }

            // ── Ret ──────────────────────────────────────────────────────
            "ret" => {
                let ty = self.parse_type()?;
                let val = if ty == IrType::Void { None } else { Some(self.parse_value()?) };
                Ok(Instr::Ret { ty, val })
            }

            // ── Unreachable ───────────────────────────────────────────────
            "unreachable" => Ok(Instr::Unreachable),

            // ── Ignored / unsupported ─────────────────────────────────────
            other => {
                log::debug!("skipping unsupported instruction: {}", other);
                // Skip rest of line tokens until we hit something that looks
                // like the start of a new instruction or block end
                self.skip_to_keyword(&["define", "declare", "ret", "br",
                                       "call", "store", "load", "phi",
                                       "alloca", "getelementptr"]);
                Ok(Instr::Unreachable)
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Basic block parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_block(&mut self, label: String) -> Result<BasicBlock> {
        let mut instrs = Vec::new();
        loop {
            match self.peek().clone() {
                Tok::RBrace | Tok::Eof => break,
                // New block label: "N:" (integer label) or "name:"
                Tok::Integer(_) | Tok::Ident(_) => {
                    // Peek ahead — if next-next is ':', it's a label
                    // We can't easily peek 2 ahead, so check if current + next = label pattern
                    // Heuristic: if we see an ident followed by ':', it's a new block
                    let saved = self.pos;
                    let tok = self.advance().clone();
                    if self.eat(&Tok::Colon) {
                        // It's a block label — restore and return current block
                        self.pos = saved;
                        break;
                    }
                    self.pos = saved;

                    // Otherwise it's an instruction without LHS assignment
                    match tok {
                        Tok::Ident(ref s) if matches!(s.as_str(),
                            "ret"|"br"|"store"|"call"|"unreachable"|"tail"|"musttail"|"switch") =>
                        {
                            match self.parse_instr(None) {
                                Ok(i)  => instrs.push(i),
                                Err(e) => { log::warn!("instr parse error: {}", e); }
                            }
                        }
                        _ => { self.advance(); } // skip
                    }
                }
                // %dst = ...
                Tok::LocalReg(dst) => {
                    let dst = dst.clone();
                    self.advance();
                    if self.eat(&Tok::Equals) {
                        match self.parse_instr(Some(dst)) {
                            Ok(i)  => instrs.push(i),
                            Err(e) => { log::warn!("instr parse error: {}", e); }
                        }
                    } else if self.eat(&Tok::Colon) {
                        // label "name:" — new block
                        self.pos -= 2; // back up
                        break;
                    }
                }
                _ => { self.advance(); }
            }
        }
        Ok(BasicBlock { label, instrs })
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Function parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_function(&mut self, is_decl: bool) -> Result<Function> {
        // skip attrs like dso_local, local_unnamed_addr, etc.
        loop {
            match self.peek() {
                Tok::Ident(s) if matches!(s.as_str(),
                    "dso_local"|"local_unnamed_addr"|"unnamed_addr"|
                    "hidden"|"protected"|"internal"|"available_externally"|
                    "linkonce_odr"|"weak"|"common"|"appending"|"extern_weak"|
                    "linkonce"|"private"|"noundef") => { self.advance(); }
                _ => break,
            }
        }

        let ret_ty = self.parse_type()?;

        let name = match self.advance().clone() {
            Tok::GlobalRef(s) => s,
            t => bail!("expected @funcname, got {:?}", t),
        };

        // Parse parameter list
        self.eat(&Tok::LParen);
        let mut params = Vec::new();
        let mut param_idx = 0u32;
        loop {
            if self.eat(&Tok::RParen) { break; }
            if self.eat_ident("...") { self.eat(&Tok::RParen); break; }
            self.skip_flags();
            let ty = self.parse_type()?;
            self.skip_flags();
            let pname = match self.peek().clone() {
                Tok::LocalReg(s) => { self.advance(); s }
                _ => { let n = format!("arg{}", param_idx); param_idx += 1; n }
            };
            params.push((ty, pname));
            if !self.eat(&Tok::Comma) { self.eat(&Tok::RParen); break; }
        }

        // Windows CRT functions defined inline by clang (linkonce_odr) but whose
        // bodies use unsupported patterns or are redirected at call sites.
        // Treat them as extern declarations — tsk-libc stubs handle them.
        // CRT/stdio functions whose bodies should be skipped.
        // tsk-libc provides these as syscall stubs (Im_SYSCALL).
        // By treating them as extern decls here, tsk-link resolves the
        // call sites directly to tsk-libc without any compiled wrapper.
        //
        // Rule: ANY function that ends up calling __stdio_common_* (which is
        // an extern CRT DLL symbol) must be stubbed — otherwise tsk-link
        // cannot resolve the chain.
        // CRT/stdio functions whose bodies are skipped.
        // tsk-libc provides these as syscall stubs.
        // IMPORTANT: sprintf/printf/vsprintf etc. are compiled as linkonce_odr
        // with bodies that call _vsprintf_l → _vsnprintf_l → __stdio_common_vsprintf
        // (an external CRT DLL function). We must skip ALL of these bodies and
        // let tsk-link resolve directly to our libc stubs.
        const CRT_STUBS: &[&str] = &[
            // CRT internals (use __stdio_common_* which is extern DLL)
            "_vfprintf_l", "_vsprintf_l", "_vsnprintf_l", "_vsnprintf",
            "__stdio_common_vfprintf", "__stdio_common_vsprintf",
            "__local_stdio_printf_options",
            "_snprintf", "_snprintf_l",
            // Standard wrappers — ALL skip to tsk-libc
            "printf",  "fprintf",  "sprintf",  "snprintf",
            "vprintf", "vfprintf", "vsprintf", "vsnprintf",
            // MSVC-specific (sometimes appear inline)
            "_printf_l", "_fprintf_l", "_sprintf_l", "_snprintf_l",
        ];
        let force_decl = CRT_STUBS.contains(&name.as_str());

        if is_decl || force_decl {
            if force_decl && !is_decl {
                // Skip the entire function body (scan to matching '}')
                let mut depth = 0i32;
                loop {
                    match self.peek() {
                        Tok::LBrace => { depth += 1; self.advance(); }
                        Tok::RBrace => {
                            self.advance();
                            depth -= 1;
                            if depth <= 0 { break; }
                        }
                        Tok::Eof => break,
                        _ => { self.advance(); }
                    }
                }
            } else {
                // Skip attributes for declare
                loop {
                    match self.peek() {
                        Tok::Ident(_) => { self.advance(); }
                        _ => break,
                    }
                }
            }
            return Ok(Function { name, ret_ty, params, blocks: vec![], is_decl: true });
        }

        // Skip function attributes until '{'
        loop {
            match self.peek() {
                Tok::LBrace => break,
                Tok::Eof    => bail!("unexpected EOF before function body"),
                _           => { self.advance(); }
            }
        }
        self.eat(&Tok::LBrace);

        // Parse basic blocks
        let mut blocks = Vec::new();
        // First block has implicit label (function name or "entry")
        let mut current_label = "entry".to_string();

        loop {
            if self.eat(&Tok::RBrace) { break; }
            if matches!(self.peek(), Tok::Eof) { break; }

            // Check for block label
            let saved = self.pos;
            match self.peek().clone() {
                Tok::Integer(n) => {
                    let label = n.to_string();
                    self.advance();
                    if self.eat(&Tok::Colon) {
                        if !blocks.is_empty() || !current_label.is_empty() {
                            // flush previous block if any
                        }
                        current_label = label;
                        continue;
                    }
                    self.pos = saved;
                }
                Tok::Ident(s) => {
                    let s = s.clone();
                    self.advance();
                    if self.eat(&Tok::Colon) {
                        current_label = s;
                        continue;
                    }
                    self.pos = saved;
                }
                _ => {}
            }

            let block = self.parse_block(current_label.clone())?;
            let is_terminator = block.instrs.last().map(|i| matches!(i,
                Instr::Ret{..} | Instr::BrUncond{..} | Instr::BrCond{..} | Instr::Unreachable
            )).unwrap_or(false);
            blocks.push(block);

            // Next block label
            match self.peek().clone() {
                Tok::Integer(n) => {
                    current_label = n.to_string();
                    self.advance();
                    self.eat(&Tok::Colon);
                }
                Tok::Ident(s) if !matches!(s.as_str(), "define"|"declare"|"attributes") => {
                    current_label = s;
                    self.advance();
                    self.eat(&Tok::Colon);
                }
                _ => {
                    if !is_terminator { break; }
                }
            }
        }

        eprintln!("[tsk-cc] function @{}: {} blocks", name, blocks.len());
        for b in &blocks { eprintln!("  block '{}': {} instrs, last={:?}", b.label, b.instrs.len(), b.instrs.last().map(|i| format!("{:?}", i).chars().take(40).collect::<String>())); }
        Ok(Function { name, ret_ty, params, blocks, is_decl: false })
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Global variable parsing
    // ─────────────────────────────────────────────────────────────────────────

    fn parse_global(&mut self, name: String) -> Result<Global> {
        // @name = [linkage] [dso_local] [global|constant] type [initializer] [, align N]
        let mut is_external_linkage = false;
        loop {
            match self.peek() {
                Tok::Ident(s) if matches!(s.as_str(),
                    "dso_local"|"local_unnamed_addr"|"unnamed_addr"|
                    "private"|"internal"|"hidden"|"common"|
                    "linkonce_odr"|"linkonce"|"weak"|"weak_odr"|"available_externally"|
                    "appending"|"extern_weak") => { self.advance(); }
                Tok::Ident(s) if s == "external" => {
                    is_external_linkage = true;
                    self.advance();
                }
                _ => break,
            }
        }
        let mutable = match self.peek() {
            Tok::Ident(s) if s == "global"   => { self.advance(); true  }
            Tok::Ident(s) if s == "constant" => { self.advance(); false }
            _ => true,
        };

        let ty = self.parse_type()?;

        // External declarations have no initializer and must not emit data.
        let init = if is_external_linkage {
            // Skip any remaining tokens on this line (e.g. alignment)
            GlobalInit::External
        } else { match self.peek().clone() {
            Tok::Ident(s) if s == "zeroinitializer" => {
                self.advance(); GlobalInit::ZeroInit
            }
            Tok::Ident(s) if s == "undef" => {
                self.advance(); GlobalInit::Undef
            }
            Tok::Integer(n) => {
                self.advance(); GlobalInit::Integer(n)
            }
            // LLVM byte-string literal: c"%d\0A\00" (array of i8 constants)
            // Tokenized as Ident("c") followed by quoted string content in Ident
            Tok::Ident(s) if s == "c" => {
                self.advance(); // consume "c"
                match self.peek().clone() {
                    Tok::Ident(raw) => {
                        // The lexer already decoded hex escapes in read_quoted()
                        let bytes: Vec<u8> = raw.chars().map(|c| c as u8).collect();
                        self.advance();
                        GlobalInit::Bytes(bytes)
                    }
                    _ => GlobalInit::ZeroInit,
                }
            }
            // Array initializer: [N x ptr] [ptr @sym0, ptr @sym1, ...]
            // This is an array of pointers to named globals — emit data relocs.
            Tok::LBracket => {
                self.advance(); // consume '['
                let mut ptrs: Vec<String> = Vec::new();
                // Parse: ptr @sym0, ptr @sym1, ... until ']'
                loop {
                    match self.peek().clone() {
                        Tok::RBracket => { self.advance(); break; }
                        Tok::Comma => { self.advance(); }
                        Tok::Ident(kw) if kw == "ptr" || kw == "i64" || kw == "i32" || kw == "i8" => {
                            self.advance(); // consume type keyword
                            // '@name' is lexed as Tok::GlobalRef(name)
                            match self.peek().clone() {
                                Tok::GlobalRef(sym) => {
                                    ptrs.push(sym.clone());
                                    self.advance();
                                }
                                Tok::Ident(kw2) if kw2 == "null" || kw2 == "zeroinitializer" => {
                                    ptrs.push(String::new()); // null ptr slot
                                    self.advance();
                                }
                                Tok::Integer(_) => {
                                    ptrs.push(String::new()); // integer in ptr slot
                                    self.advance();
                                }
                                _ => {} // skip unknown
                            }
                        }
                        Tok::Ident(kw) if kw == "null" || kw == "zeroinitializer" => {
                            ptrs.push(String::new());
                            self.advance();
                        }
                        _ => { self.advance(); } // skip unknown tokens
                    }
                }
                if ptrs.is_empty() {
                    GlobalInit::ZeroInit
                } else {
                    GlobalInit::PointerArray(ptrs)
                }
            }
            // Single pointer initializer: ptr @sym (lexed as GlobalRef)
            Tok::Ident(kw) if kw == "ptr" => {
                self.advance(); // consume 'ptr'
                match self.peek().clone() {
                    Tok::GlobalRef(sym) => {
                        let s = sym.clone();
                        self.advance();
                        GlobalInit::PointerTo(s)
                    }
                    Tok::Ident(kw2) if kw2 == "null" => {
                        self.advance();
                        GlobalInit::ZeroInit
                    }
                    _ => GlobalInit::ZeroInit,
                }
            }
            _ => GlobalInit::ZeroInit,
        } }; // close match + else

        let mut align = ty.byte_size().max(1);
        loop {
            match self.peek() {
                Tok::Comma => {
                    self.advance();
                    if self.eat_ident("align") {
                        align = self.expect_integer()? as usize;
                    }
                }
                Tok::Ident(s) if s == "align" => {
                    self.advance();
                    align = self.expect_integer()? as usize;
                }
                _ => break,
            }
        }

        Ok(Global { name, ty, mutable, init, align })
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Module parsing — top level
    // ─────────────────────────────────────────────────────────────────────────

    pub fn parse_module(&mut self) -> Result<Module> {
        let mut module = Module::default();

        // ── Pre-pass: collect ALL type definitions first ──────────────────────
        // LLVM IR may place type declarations after function definitions
        // (e.g. forward references). By collecting types in one pass and
        // resetting position, we guarantee type_defs is fully populated
        // before any function body references a named struct type.
        let saved_pos = self.pos;
        loop {
            match self.peek().clone() {
                Tok::Eof => break,
                Tok::LocalReg(name) => {
                    let name = name.clone();
                    self.advance();
                    if self.eat(&Tok::Equals) {
                        if let Tok::Ident(s) = self.peek().clone() {
                            if s == "type" {
                                self.advance();
                                match self.parse_type() {
                                    Ok(ty) => {
                                        log::debug!("pre-pass type def %{} = {:?}", name, ty);
                                        eprintln!("[tsk-cc] type_def: %{} = {:?}", name, ty);
                                        self.type_defs.insert(name, ty);
                                    }
                                    Err(e) => { log::warn!("pre-pass type def error: {}", e); }
                                }
                                continue;
                            }
                        }
                    }
                    // Not a type def — skip to next line
                    while !matches!(self.peek(), Tok::Eof | Tok::Ident(_) | Tok::GlobalRef(_) | Tok::LocalReg(_)) {
                        self.advance();
                    }
                }
                _ => { self.advance(); }
            }
        }
        // Reset to beginning for the main parse pass
        self.pos = saved_pos;

        loop {
            match self.peek().clone() {
                Tok::Eof => break,

                Tok::Ident(s) if s == "define" => {
                    self.advance();
                    match self.parse_function(false) {
                        Ok(f)  => { log::debug!("parsed function @{}", f.name); module.functions.push(f); }
                        Err(e) => { log::warn!("function parse error: {}", e); self.skip_to_keyword(&["define","declare"]); }
                    }
                }

                Tok::Ident(s) if s == "declare" => {
                    self.advance();
                    match self.parse_function(true) {
                        Ok(f)  => module.functions.push(f),
                        Err(e) => { log::warn!("declare parse error: {}", e); }
                    }
                }

                // Type definition: %struct.foo = type { i64, i64, i32 }
                Tok::LocalReg(name) => {
                    let name = name.clone();
                    self.advance();
                    if self.eat(&Tok::Equals) {
                        if let Tok::Ident(s) = self.peek().clone() {
                            if s == "type" {
                                self.advance();
                                match self.parse_type() {
                                    Ok(ty) => {
                                        log::debug!("type def %{} = {:?}", name, ty);
                                        self.type_defs.insert(name, ty);
                                    }
                                    Err(e) => { log::warn!("type def parse error: {}", e); }
                                }
                                continue;
                            }
                        }
                    }
                    // Not a type def — skip line
                    self.skip_to_keyword(&["define","declare"]);
                }

                Tok::GlobalRef(name) => {
                    let name = name.clone();
                    self.advance();
                    if self.eat(&Tok::Equals) {
                        match self.parse_global(name) {
                            Ok(g)  => module.globals.push(g),
                            Err(e) => { log::warn!("global parse error: {}", e); }
                        }
                    }
                }

                // source_filename, target datalayout, target triple, attributes, metadata
                Tok::Ident(s) if matches!(s.as_str(),
                    "source_filename"|"target"|"attributes"|"define"|"declare") => {
                    self.skip_to_keyword(&["define","declare"]);
                }

                _ => { self.advance(); }
            }
        }

        // Transfer type definitions to module for use by codegen (GEP struct offsets)
        module.type_defs = std::mem::take(&mut self.type_defs);

        Ok(module)
    }
}
