// tsk-dbg/src/main.rs
// Author: Echopraxium with the collaboration of Claude AI
// Version: 0.1.0
//
// DAP-compatible debugger for TriskeleVM.
// Listens on TCP :4711 (default), communicates with VS Code via JSON/DAP.
//
// Usage:
//   tsk-dbg wolf3d_v2_clean.tvmx --symbols wolf3d_v2_clean.sym
//   tsk-dbg wolf3d_v2_clean.tvmx --symbols wolf3d_v2_clean.sym --port 4712

mod dap;
mod session;
mod disasm;
mod symbols;
mod vm_runner;

use clap::Parser;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[clap(
    name    = "tsk-dbg",
    version = "0.1.0",
    about   = "DAP debugger for TriskeleVM — connects to VS Code on TCP"
)]
pub struct Cli {
    /// .tvmx binary to debug
    #[clap(value_name = "BINARY")]
    pub binary: PathBuf,

    /// Symbol table (.sym) generated by tsk-asm (label -> PC address)
    #[clap(long, short = 's', value_name = "FILE")]
    pub symbols: Option<PathBuf>,

    /// TCP port for DAP server (default: 4711)
    #[clap(long, short = 'p', default_value = "4711")]
    pub port: u16,

    /// Memory size for VM (bytes, default: 16MB)
    #[clap(long, default_value = "67108864")]  // 64MB — covers LOAD_BASE(0x1000) + stack + heap
    pub mem_size: usize,

    /// Maximum instructions to execute before pausing (0 = unlimited)
    #[clap(long, default_value = "0")]
    pub max_instructions: u64,

    /// Verbose logging
    #[clap(long, short = 'v')]
    pub verbose: bool,
}

#[tokio::main(flavor = "multi_thread", worker_threads = 2)]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    // Init logger
    let log_level = if cli.verbose { "debug" } else { "info" };
    env_logger::Builder::from_env(
        env_logger::Env::default().default_filter_or(log_level)
    ).init();

    log::info!("tsk-dbg v0.1.0 - TriskeleVM DAP Debugger");
    log::info!("Binary  : {}", cli.binary.display());
    log::info!("Symbols : {}", cli.symbols.as_ref()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|| "(none)".into()));
    log::info!("DAP port: {}", cli.port);

    // Load binary
    let bytecode = std::fs::read(&cli.binary)
        .map_err(|e| anyhow::anyhow!("Cannot read binary '{}': {}", cli.binary.display(), e))?;

    // Load symbol table (optional but strongly recommended)
    let sym_table = if let Some(sym_path) = &cli.symbols {
        symbols::SymbolTable::load(sym_path)?
    } else {
        log::warn!("No symbol file - breakpoints by label unavailable.");
        symbols::SymbolTable::empty()
    };

    // Start DAP server
    let addr = format!("127.0.0.1:{}", cli.port);
    log::info!("Waiting for VS Code DAP connection on {} ...", addr);
    println!("tsk-dbg: DAP server listening on {}", addr);
    println!("         In VS Code: F5 -> 'TriskeleVM Debug' launch config");

    dap::server::run_server(addr, bytecode, sym_table, cli.mem_size, cli.max_instructions).await
}
