// tsk-dbg/src/symbols.rs
// Author: Echopraxium with the collaboration of Claude AI
//
// Symbol table: label → PC address, generated by tsk-asm --emit-symbols.
//
// .sym file format (one entry per line):
//   <label> <hex_address>
//   ray_loop 0x00A4
//   draw_col 0x01B8
//   sin_table 0x0400
//
// Lines starting with '#' are comments.

use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct SymbolTable {
    /// label → byte address in .tvmx bytecode
    label_to_addr: HashMap<String, u64>,
    /// address → label (reverse, for display)
    addr_to_label: HashMap<u64, String>,
}

impl SymbolTable {
    /// Load from a .sym file produced by tsk-asm.
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("Cannot read symbol file '{}': {}", path.display(), e))?;

        let mut label_to_addr = HashMap::new();
        let mut addr_to_label = HashMap::new();

        for (lineno, line) in content.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let parts: Vec<&str> = line.splitn(2, ' ').collect();
            if parts.len() != 2 {
                log::warn!("symbols.sym line {}: skipped (bad format): {}", lineno + 1, line);
                continue;
            }

            let label = parts[0].to_string();
            let addr_str = parts[1].trim();
            let addr = parse_addr(addr_str)
                .ok_or_else(|| anyhow::anyhow!(
                    "symbols.sym line {}: cannot parse address '{}' for label '{}'",
                    lineno + 1, addr_str, label
                ))?;

            addr_to_label.insert(addr, label.clone());
            label_to_addr.insert(label, addr);
        }

        // Symbols from tsk-asm are offsets from bytecode start (0x0000).
        // tsk-dbg loads code at LOAD_BASE (0x1000) — adjust all addresses.
        use crate::vm_runner::LOAD_BASE;
        let label_to_addr: HashMap<String, u64> = label_to_addr
            .into_iter()
            .map(|(k, v)| (k, v + LOAD_BASE))
            .collect();
        let addr_to_label: HashMap<u64, String> = addr_to_label
            .into_iter()
            .map(|(k, v)| (k + LOAD_BASE, v))
            .collect();

        log::info!("Loaded {} symbols (base offset: 0x{:04X}).", label_to_addr.len(), LOAD_BASE);
        Ok(Self { label_to_addr, addr_to_label })
    }

    /// Empty table (no .sym file provided).
    pub fn empty() -> Self {
        Self {
            label_to_addr: HashMap::new(),
            addr_to_label: HashMap::new(),
        }
    }

    /// Look up a label → address.
    pub fn addr_of(&self, label: &str) -> Option<u64> {
        self.label_to_addr.get(label).copied()
    }

    /// Look up an address → nearest label (exact match or closest ≤ addr).
    pub fn label_at(&self, addr: u64) -> Option<&str> {
        // Exact match first
        if let Some(label) = self.addr_to_label.get(&addr) {
            return Some(label.as_str());
        }
        // Nearest label ≤ addr
        self.addr_to_label
            .iter()
            .filter(|(a, _)| **a <= addr)
            .max_by_key(|(a, _)| *a)
            .map(|(_, l)| l.as_str())
    }

    /// All labels sorted by address (for display).
    pub fn all_sorted(&self) -> Vec<(u64, &str)> {
        let mut v: Vec<(u64, &str)> = self.addr_to_label
            .iter()
            .map(|(a, l)| (*a, l.as_str()))
            .collect();
        v.sort_by_key(|(a, _)| *a);
        v
    }

    pub fn is_empty(&self) -> bool {
        self.label_to_addr.is_empty()
    }
}

fn parse_addr(s: &str) -> Option<u64> {
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u64::from_str_radix(hex, 16).ok()
    } else {
        s.parse::<u64>().ok()
    }
}
