# projects/sdl_test/pipeline.toml
# Author: Echopraxium with the collaboration of Claude AI
name    = "sdl_test"
type    = "tasm"
sources = ["sdl_test.tasm"]
entry   = "main"
libs    = []
sdl2    = true
