// tsk-cc/src/main.rs
// Author: Echopraxium with the collaboration of Claude AI
// Version: 0.3.0
//
// tsk-cc — LLVM IR (.ll) → TriskeleVM object (.tobj)

mod ir;
mod parser;
mod codegen;

use std::path::PathBuf;
use anyhow::{bail, Result};
use clap::Parser;
use triskele_common::tvm::{TvmBuilder, SectionType};

// ─────────────────────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Parser, Debug)]
#[clap(
    name     = "tsk-cc",
    version  = "0.3.0",
    about    = "TriskeleVM C compiler — LLVM IR (.ll) → TriskeleVM object (.tobj)"
)]
struct Args {
    /// Input LLVM IR file (.ll)
    input: PathBuf,

    /// Output object file (.tobj). Default: <input>.tobj
    #[clap(short = 'o', long)]
    output: Option<PathBuf>,

    /// Print parsed IR summary (functions, globals, block counts)
    #[clap(long)]
    dump_ir: bool,

    /// Print generated bytecode as annotated hex
    #[clap(long)]
    dump_asm: bool,

    /// Verbose output
    #[clap(short, long)]
    verbose: bool,
}

// ─────────────────────────────────────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────────────────────────────────────

fn main() {
    env_logger::init();
    let args = Args::parse();

    if let Err(e) = run(args) {
        eprintln!("tsk-cc error: {}", e);
        std::process::exit(1);
    }
}

fn run(args: Args) -> Result<()> {
    // ── 1. Read input ────────────────────────────────────────────────────────
    let input_path = &args.input;
    if !input_path.exists() {
        bail!("input file not found: {}", input_path.display());
    }
    let src = std::fs::read_to_string(input_path)?;

    if args.verbose {
        eprintln!("[tsk-cc] Parsing {}  ({} bytes)",
            input_path.display(), src.len());
    }

    // ── 2. Parse LLVM IR ─────────────────────────────────────────────────────
    let mut p = parser::Parser::new(&src);
    let module = p.parse_module()?;

    if args.dump_ir || args.verbose {
        eprintln!("[tsk-cc] Module: {} global(s), {} function(s)",
            module.globals.len(), module.functions.len());
        for f in &module.functions {
            eprintln!("  {} @{}  ({} params, {} blocks{})",
                if f.is_decl { "declare" } else { "define " },
                f.name,
                f.params.len(),
                f.blocks.len(),
                if f.is_decl { " [external]" } else { "" });
        }
        for g in &module.globals {
            eprintln!("  global @{}  ({} bytes)",
                g.name, g.ty.byte_size());
        }
    }

    // ── 3. Code generation ───────────────────────────────────────────────────
    if args.verbose {
        eprintln!("[tsk-cc] Generating bytecode...");
    }
    let cg_out = codegen::generate_module(&module)?;

    if args.dump_asm || args.verbose {
        eprintln!("[tsk-cc] Generated {} function(s):", cg_out.functions.len());
        for (name, code) in &cg_out.functions {
            eprintln!("  @{}  {} bytes  ({} instructions)",
                name, code.len(), code.len() / 4);
            if args.dump_asm {
                dump_bytecode(name, code);
            }
        }
        if !cg_out.data.is_empty() {
            eprintln!("[tsk-cc] Data section: {} bytes", cg_out.data.len());
        }
    }

    if cg_out.functions.is_empty() {
        bail!("no functions generated — is the input file valid LLVM IR?");
    }

    // ── 4. Emit .tobj ────────────────────────────────────────────────────────
    let output_path = args.output.unwrap_or_else(|| {
        let stem = input_path.file_stem().unwrap_or_default();
        input_path.with_file_name(format!("{}.tobj",
            stem.to_string_lossy()))
    });

    let tvx = build_tobj(&cg_out)?;
    std::fs::write(&output_path, &tvx)?;

    eprintln!("[tsk-cc] {} → {}  ({} bytes)",
        input_path.display(), output_path.display(), tvx.len());

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Build .tobj from CodegenOutput
// ─────────────────────────────────────────────────────────────────────────────

fn build_tobj(cg: &codegen::CodegenOutput) -> Result<Vec<u8>> {
    // Concatenate all function bytecodes into one code section.
    let mut code = Vec::new();
    let entry_offset: u32 = 0;   // first function is always entry

    for (_name, func_code) in &cg.functions {
        code.extend_from_slice(func_code);
        // Align to 4 bytes
        while code.len() % 4 != 0 { code.push(0); }
    }

    // Build symbol table section: name\0 offset32 (simple flat format)
    // For code symbols: offset = byte offset within code section
    // For data symbols: offset = byte offset within data section | 0x8000_0000 (flag)
    let mut symtab = Vec::new();
    let mut sym_offset: u32 = 0;
    for (name, func_code) in &cg.functions {
        symtab.extend_from_slice(name.as_bytes());
        symtab.push(0u8);
        symtab.extend_from_slice(&sym_offset.to_le_bytes());
        sym_offset += ((func_code.len() as u32) + 3) & !3;
    }
    // Data globals: flag bit 31 = 1 means data symbol
    for (name, data_off, _size) in &cg.globals {
        let flagged = (*data_off as u32) | 0x8000_0000u32;
        symtab.extend_from_slice(name.as_bytes());
        symtab.push(0u8);
        symtab.extend_from_slice(&flagged.to_le_bytes());
    }

    // Build relocation table: [u32 code_offset][symbol_name\0] for each fixup
    // tsk-link will patch D_MOV_I/F_CALL instructions at these offsets
    // with the resolved symbol addresses.
    let mut reltab: Vec<u8> = Vec::new();
    for (name, func_code) in &cg.functions {
        let _ = name;
        let _ = func_code;
    }
    // Use cg.relocations if available
    for (abs_offset, sym_name) in &cg.relocations {
        reltab.extend_from_slice(&(*abs_offset as u32).to_le_bytes());
        reltab.extend_from_slice(sym_name.as_bytes());
        reltab.push(0);
    }

    let mut builder = TvmBuilder::new()
        .entry(entry_offset)
        .add_section(SectionType::Code, 0x02, code);

    if !cg.data.is_empty() {
        builder = builder.add_section(SectionType::Data, 0x01, cg.data.clone());
    }
    if !reltab.is_empty() {
        builder = builder.add_section(SectionType::Reltab, 0x07, reltab);
    }
    if !symtab.is_empty() {
        builder = builder.add_section(SectionType::Symtab, 0x0E, symtab);
    }

    Ok(builder.build())
}

// ─────────────────────────────────────────────────────────────────────────────
// Debug: dump bytecode as annotated hex
// ─────────────────────────────────────────────────────────────────────────────

fn dump_bytecode(func_name: &str, code: &[u8]) {
    use triskele_common::isa::Opcode;

    eprintln!("  --- @{} ---", func_name);
    for (i, chunk) in code.chunks(4).enumerate() {
        if chunk.len() < 4 { break; }
        let word = u32::from_le_bytes(chunk.try_into().unwrap());
        let opcode_byte = (word >> 24) as u8;
        let mnemonic = Opcode::from_byte(opcode_byte)
            .map(|op| op.mnemonic().to_string())
            .unwrap_or_else(|| format!("0x{:02X}", opcode_byte));
        let dst    = (word >> 19) & 0x1F;
        let s1     = (word >> 14) & 0x1F;
        let s2     = (word >>  9) & 0x1F;
        let imm    = (word & 0x0007_FFFF) as i32;
        let imm_s  = if imm & 0x0004_0000 != 0 { imm as i32 | !0x0007_FFFFi32 } else { imm };
        eprintln!("    {:4}  {:08X}  {:<16} R{} R{} R{}  imm={:+}",
            i * 4, word, mnemonic, dst, s1, s2, imm_s);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::Parser;
    use crate::codegen::generate_module;

    #[test]
    fn test_scalediv_compile() {
        let ir = r#"
define i32 @ScaleDiv(i32 %0, i32 %1) {
  %3 = icmp eq i32 %1, 0
  br i1 %3, label %ret_zero, label %do_div

ret_zero:
  ret i32 0

do_div:
  %5 = sdiv i32 %0, %1
  ret i32 %5
}
"#;
        let mut p = Parser::new(ir);
        let module = p.parse_module().unwrap();
        assert_eq!(module.functions.len(), 1);
        assert_eq!(module.functions[0].name, "ScaleDiv");
        assert_eq!(module.functions[0].blocks.len(), 3);

        let cg = generate_module(&module).unwrap();
        assert_eq!(cg.functions.len(), 1);
        assert!(!cg.functions[0].1.is_empty(), "codegen produced no bytecode");
        assert_eq!(cg.functions[0].1.len() % 4, 0, "bytecode not word-aligned");
        eprintln!("ScaleDiv: {} bytes ({} instructions)",
            cg.functions[0].1.len(), cg.functions[0].1.len() / 4);
    }

    #[test]
    fn test_global_array() {
        let ir = r#"
@tilemap = dso_local global [4096 x i8] zeroinitializer, align 16

define i32 @read_tile(i32 %0) {
  %2 = sext i32 %0 to i64
  %3 = getelementptr inbounds [4096 x i8], ptr @tilemap, i64 0, i64 %2
  %4 = load i8, ptr %3, align 1
  %5 = zext i8 %4 to i32
  ret i32 %5
}
"#;
        let mut p = Parser::new(ir);
        let module = p.parse_module().unwrap();
        assert_eq!(module.globals.len(), 1);
        assert_eq!(module.globals[0].name, "tilemap");

        let cg = generate_module(&module).unwrap();
        assert!(!cg.data.is_empty(), "data section should contain tilemap");
        eprintln!("tilemap data: {} bytes", cg.data.len());
    }

    #[test]
    fn test_multi_function_compile() {
        let ir = r#"
define i32 @add(i32 %0, i32 %1) {
  %3 = add i32 %0, %1
  ret i32 %3
}

define i32 @mul(i32 %0, i32 %1) {
  %3 = mul i32 %0, %1
  ret i32 %3
}

define i32 @madd(i32 %0, i32 %1, i32 %2) {
  %4 = mul i32 %0, %1
  %5 = add i32 %4, %2
  ret i32 %5
}
"#;
        let mut p = Parser::new(ir);
        let module = p.parse_module().unwrap();
        assert_eq!(module.functions.len(), 3);

        let cg = generate_module(&module).unwrap();
        assert_eq!(cg.functions.len(), 3);

        let tobj = build_tobj(&cg).unwrap();
        assert!(!tobj.is_empty());
        eprintln!("multi-function → {} bytes .tobj", tobj.len());
    }
}